# Generated by Django 3.2.13 on 2022-09-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesevent', to='events.event')),
            ],
        ),
    ]
