# Generated by Django 3.2.13 on 2022-09-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_imagesevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
