# Generated by Django 3.2.13 on 2022-09-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='event',
            name='short_description',
            field=models.CharField(default='hola', max_length=80),
            preserve_default=False,
        ),
    ]
