# Generated by Django 3.2.13 on 2022-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220927_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesevent',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
