# Generated by Django 3.2.13 on 2022-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_imagesevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesevent',
            name='image',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
    ]
