# Generated by Django 3.2.13 on 2022-10-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_imagesevent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('BIENVENIDA A FAMILIAS DE PRIMER AÑO', 'BIENVENIDA A FAMILIAS DE PRIMER AÑO'), ('TALLERES PEDAGÓGICOS', 'TALLERES PEDAGÓGICOS'), ('CONFERENCIAS', 'CONFERENCIAS'), ('RETIROS ESPIRITUALES', 'RETIROS ESPIRITUALES'), ('INTEGRACION DE LOS PADRES A LA LABOR EDUCATIVA', 'INTEGRACION DE LOS PADRES A LA LABOR EDUCATIVA'), ('LOCRO DEL EXALUMNO SALESIANO DEL VILLADA', 'LOCRO DEL EXALUMNO SALESIANO DEL VILLADA'), ('UPF SOLIDARIA', 'UPF SOLIDARIA'), ('DIA DEL EDUCADOR', 'DIA DEL EDUCADOR'), ('BICICLETEADA SALESIANA', 'BICICLETEADA SALESIANA'), ('ASADO DE FIN DE AÑO', 'ASADO DE FIN DE AÑO'), ('VALLE DE LA INMACULADA', 'VALLE DE LA INMACULADA')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
