# Generated by Django 3.2.13 on 2022-08-09 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('on_circulation', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField()),
                ('tel', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Usado', 'Usado'), ('Casi nuevo', 'Casi nuevo'), ('Excelente', 'Excelente')], max_length=15)),
                ('title', models.CharField(max_length=60)),
                ('author', models.CharField(blank=True, max_length=60, null=True)),
                ('matter', models.CharField(max_length=60)),
                ('age', models.CharField(choices=[('1° Año', '1° Año'), ('2° Año', '2° Año'), ('3° Año', '3° Año'), ('4° Año', '4° Año'), ('5° Año', '5° Año'), ('6° Año', '6° Año'), ('7° Año', '7° Año')], max_length=15)),
                ('editorial', models.CharField(blank=True, max_length=60, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('on_circulation', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField()),
                ('tel', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Usado', 'Usado'), ('Casi nuevo', 'Casi nuevo'), ('Excelente', 'Excelente')], max_length=15)),
                ('type_of_garment', models.CharField(max_length=60)),
                ('size', models.CharField(choices=[('XXS', 'XXS'), ('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=10)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('on_circulation', models.BooleanField(default=True)),
                ('price', models.PositiveIntegerField()),
                ('tel', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Usado', 'Usado'), ('Casi nuevo', 'Casi nuevo'), ('Excelente', 'Excelente')], max_length=15)),
                ('tool', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagestool', to='marketplace.tool')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesClothing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagescloth', to='marketplace.clothing')),
            ],
        ),
        migrations.CreateModel(
            name='ImagesBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesbook', to='marketplace.book')),
            ],
        ),
    ]
