# Generated by Django 3.2.13 on 2022-09-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_clothing_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-published_date', '-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'ordering': ['-published_date', '-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'ordering': ['-published_date', '-creation_date']},
        ),
    ]
