# Generated by Django 3.2.13 on 2022-10-03 00:17

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_auto_20220927_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
