# Generated by Django 3.2.13 on 2022-09-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='published_date',
        ),
    ]
