# Generated by Django 3.2.13 on 2022-09-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pool',
            options={'ordering': ['-id']},
        ),
    ]
