# Generated by Django 3.2.13 on 2022-10-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0005_alter_pool_alternative_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='lat',
            field=models.CharField(default=60, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='lng',
            field=models.CharField(default=23, max_length=30),
            preserve_default=False,
        ),
    ]
