# Generated by Django 3.2.13 on 2022-10-11 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_auto_20221004_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
